### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by jcchuang** [mozilla/ad-analysis-for-facebook-disabled#6]
- [x] Code by @jcchuang 
  - [x] Toolbar icon
  - [x] Badge 
  - [x] Grey out after first use #5 
- [x] Copy by @mheubusch #3 
- [x] Design review
- [x] Legal review
- [x] Code review by @biancadanforth #2 
- [x] QA review by @madalincm #1 
- [x] Bugs and Workarounds
  - [x] Remove terser workaround after `terser@3.16.0` broke `webpack` on Feb 2nd #7 
  - [x] Remove unnecessary scrollbar per QA testing #8 
- [x] Publish
  - [x] Upload the extension to AMO
  - [x] Update AMO listing
  - [x] Turn this repository public #4
